//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biznis.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int idContact { get; set; }
        public string idUser { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
