//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biznis.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header
    {
        public int idHeader { get; set; }
        public Nullable<int> idImage { get; set; }
        public string heading { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
