//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biznis.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int idPost { get; set; }
        public string idUser { get; set; }
        public string heading { get; set; }
        public string paragraph { get; set; }
        public Nullable<System.DateTime> publish { get; set; }
        public Nullable<int> idImg { get; set; }
        public Nullable<int> idCategory { get; set; }
        public string ImageAbout { get; set; }
        public string paragraph2 { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        public virtual Image Image { get; set; }
    }
}
